// <auto-generated />
using System;
using Dangl.OpenCDE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dangl.OpenCDE.Migrations
{
    [DbContext(typeof(CdeDbContext))]
    [Migration("20260915165909_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.CdeAppFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FileAvailableInStorage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MimeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerName");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FileName");

                    b.HasIndex("MimeTypeId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.CdeAppFileMimeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MimeType")
                        .IsUnique();

                    b.ToTable("FileMimeTypes");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.CdeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentDownloadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationInformationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCallbackUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OpenCdeDocumentDownloadSessions");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("OpenCdeDocumentSelections");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentUploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationInformationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCallbackUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SelectedProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("OpenCdeDocumentUploadSessions");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.PendingOpenCdeUploadFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedCdeDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UploadSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LinkedCdeDocumentId");

                    b.HasIndex("UploadSessionId");

                    b.ToTable("PendingOpenCdeUploadFiles");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdenticonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.CdeAppFile", b =>
                {
                    b.HasOne("Dangl.OpenCDE.Data.Models.CdeUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Dangl.OpenCDE.Data.Models.CdeAppFileMimeType", "MimeType")
                        .WithMany()
                        .HasForeignKey("MimeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MimeType");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.Document", b =>
                {
                    b.HasOne("Dangl.OpenCDE.Data.Models.CdeAppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("Dangl.OpenCDE.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentDownloadSession", b =>
                {
                    b.HasOne("Dangl.OpenCDE.Data.Models.CdeUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentSelection", b =>
                {
                    b.HasOne("Dangl.OpenCDE.Data.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dangl.OpenCDE.Data.Models.CdeUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentUploadSession", b =>
                {
                    b.HasOne("Dangl.OpenCDE.Data.Models.Project", "SelectedProject")
                        .WithMany()
                        .HasForeignKey("SelectedProjectId");

                    b.HasOne("Dangl.OpenCDE.Data.Models.CdeUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedProject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.PendingOpenCdeUploadFile", b =>
                {
                    b.HasOne("Dangl.OpenCDE.Data.Models.Document", "LinkedCdeDocument")
                        .WithMany()
                        .HasForeignKey("LinkedCdeDocumentId");

                    b.HasOne("Dangl.OpenCDE.Data.Models.OpenCdeDocumentUploadSession", "UploadSession")
                        .WithMany("PendingFiles")
                        .HasForeignKey("UploadSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedCdeDocument");

                    b.Navigation("UploadSession");
                });

            modelBuilder.Entity("Dangl.OpenCDE.Data.Models.OpenCdeDocumentUploadSession", b =>
                {
                    b.Navigation("PendingFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
